#pragma once

enum class OBJ_TYPE				{ PLAYER, ENEMY, NPC, ITEM, PROJECTILE, TILE, EFFECT, PORTAL, PARTICLE, TRIGGER, UI = 31, TYPEEND = 32 };

enum class COMPONENT_TYPE		{ TRANSFORM, COLLIDER, ANIMATOR, RIGIDBODY, TYPEEND };

enum class UI_TYPE				{ FIXED, MOVABLE, TYPEEND };

enum class FONT_SIZE			{ SMALL, MEDIUM, LARGE, PLUS_LARGE, SUPER_LARGE, TYPEEND };

enum class FONT_TYPE			{ DEFAULT, GOTHIC, RETRO, TYPEEND };

enum class SCENE_TYPE			{ TITLE, LOADING, VILLAGE, FIELD, BOSS, RESULT, EDITOR, TYPEEND };

enum class EVENT_TYPE			{ ADD_OBJ, DEL_OBJ, RMV_OBJ, CHANGE_SCENE, CHANGE_AI_STATE, TYPEEND };

enum class DIR_TYPE				{ DOWN, UP, LEFT, RIGHT, NONE, TYPEEND };

enum class RENDER_ORDER			{ PORTAL, GAMEOBJECT, EFFECT, UI, TYPEEND };

enum class SKILL_KEY_TYPE		{ Q, SPACE, LBTN, RBTN, E, R, TYPEEND };

enum class MOUSE_TYPE			{ LBTN, MBTN, RBTN, TYPEEND };

enum class INPUT_TYPE			{ KEY, MOUSE, TYPEEND };

enum class TILE_TYPE			{ WALL, DEADZONE, TYPEEND }; 


enum class CLOSE_ENEMY_STATE	{ SPAWN, CHASE, ATTACK, HURT, DEAD, TYPEEND }; // HURT with Knockback

enum class BLOB_STATE			{ SPAWN, IDLE, JUMP, HURT, DEAD, TYPEEND };

enum class ITEM_TYPE			{ GOLD, ITEM, SKILL, TYPEEND };

enum CHANNELID					{ SOUND_TITLE, SOUND_MENU, SOUND_BLOB, SOUND_CYCLOPS, SOUND_GHOUL, SOUND_CAMERA, SOUND_PORTAL, SOUND_PLAYER, SOUND_PLAYER_SKILL, SOUND_PLAYER_MOVE, SOUND_BOSS, SOUND_BGM, MAXCHANNEL };
